server:
  port: 8080

grpc:
  client:
    GLOBAL:
      negotiationType: PLAINTEXT
    target-server:
      address: static://${SERVER_IP:localhost}:${SERVER_PORT:9090}

grpc-server:
  url: ${SERVER_IP:localhost}
  port: ${SERVER_PORT:9090}

spring:
  application:
    name: grpc-client

logging:
  level:
    io.grpc: INFO
    com.pranjal: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS dd/MM/yyyy} %clr(%-5level) %clr([%thread]){blue} %logger{60} %clr([%X{requestId}]){cyan} --- %msg %n"
